use_default_settings: true

server:
  secret_key: "change-me-to-random-secret-key-for-searxng-instance"
  limiter: false
  image_proxy: false

search:
  safe_search: 0
  autocomplete: "google"
  default_lang: "ru"
  formats:
    - html
    - json
